name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-calc .

      - name: Run Docker container
        run: docker run -d -p 5000:8000 --name my-calc-container my-calc

      - name: Run tests
        run: docker exec my-calc-container python -m unittest discover -s tests
